<?xml version="1.0"?>
<robot name="omnidirectional_wheel" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="M_PI" value="3.1415926535897931" />
  <!-- Wheels -->
  <xacro:property name="omni_wheel_radius" value="0.073" />
  <xacro:property name="omni_wheel_height" value="0.070" />
  <xacro:property name="omni_wheel_mass" value="0.01" />

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
              izz="${m*r*r/2}"
     />
  </xacro:macro>

  <xacro:macro name="omni_wheel" params="prefix parent *origin hq">

    <!--WHEEL TIRE -->
    <joint name="${prefix}_wheel_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}_wheel_link"/>
      <xacro:insert_block name="origin" />
      <axis xyz="0 1 0" rpy="0 0 0" />
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}_wheel_link">
      <visual>
        <!-- HIGH RESOLUTION WHEELS -->
        <xacro:if value="${hq}">
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
				    <mesh filename="package://hr_recycler_description/meshes/wheels/hr_recycler_omni_wheel_fake.dae" scale="0.5 0.6 0.5"/>
          </geometry>
        </xacro:if>
       <!-- LOW RESOLUTION WHEELS -->
        <xacro:unless value="${hq}">
          <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
          <geometry>
            <cylinder length="${omni_wheel_height}" radius="${omni_wheel_radius}" />
          </geometry>
        </xacro:unless>
      </visual>

      <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
         <sphere radius="${omni_wheel_radius*0.35}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0.0001</mu>
            <mu2>0.0001</mu2>
          </ode>
        </friction>
			</surface>
      </collision>

      <inertial>
        <mass value="${wheel_mass}" />
        <origin xyz="0 0 0" />
        <cylinder_inertia  m="${omni_wheel_mass}" r="${omni_wheel_radius}" h="${omni_wheel_height}" />
        <!-- inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001" / -->
      </inertial>
    </link>

    <gazebo reference="${prefix}wheel">
		<mu1 value="0"/>
		<mu2 value="0"/>
		<kp value="10000000.0" />
		<kd value="1.0" />
		<fdir1 value="1 0 0"/>
		<material>Gazebo/Black</material>
		<turnGravityOff>false</turnGravityOff>
    </gazebo>

  </xacro:macro>

</robot>
